### ISSUE TITLE
Correccion

### ISSUE THREAD

**Issue by tomasemanuel** [Sh4rkzDev/AlgorithmsTheory#1]
Buenas chicos, les hago la devolucion.
Tras algunos idas y vueltas con los profes, su nota es un 6, y la principal razon fue porque no se argumento lo suficiente la optimalidad del algoritmo. 
- Tienen que demostrar que lo que encontraron es optimo. Aunque no buscabamos una demostracion matematica ( ya van a tener tiempo para eso), queriamos una demostracion por ejemplo un grafico de barras demostrando la sumatoria de los videos vistos por scaloni, y abajo las diferentes formas de resolver el problema, agarrarlo como viene, ordenarlo de mayor a menor, de menor a mayor, o otra cosa que se les ocurra. Su justificacion de que el algoritmo era optimo fue escasa, casi nula.
- Por otro lado, , por esto no se baja puntos, pero formalicen lo que dicen. Por ejemplo cuando dicen que no importa como este ordenado los tiempos de scaloni, pudieron haber puesto una igualdad matematica con la sumatoria de los videos a ver de scaloni
- Esta frase:" A su vez, se puede ver que se asemeja a la complejidad indicada, ya que la tendencia es aproximadamente lineal en t´erminos de O (n log n).", Me dejo perplejo, a que se refieren ahi ? A ver, en terminos matematicos, a numeros muy grandes, como la derivada de logaritmo es 1/n, la diferencia entre lo lineal y lo logaritmico * n es casi imperceptible , pero nuevamente, tienen que aclarar eso, no se puede dejar a merced del lector.
- Una buena forma de corroborar la complejidad del algoritmo podria haber sido teniendo otra linea comprendiendo el O(log n *n) para demostrar que iba acorde a dicha complejidad
- No hace falta que expliquen en el informe como agarran los datos del input, son datos que se quedan en el codigo, pueden documentar en el codigo que hace cada funcion, pero en el informe irian datos relacionados con la optimalidad, complejidad, mediciones, entre otras cosas... (Aunque sabemos que el input de los datos no puede dar mas que n porque sino el algoritmo no seria bueno, se podria dejar comentado)
- Otra cosa, la cantidad de elementos no me parece muy grande que digamos, fijense que el tiempo de resolucion es muyyy bajo, podrian haberle puesto mas y esperar que se puedan procesar mas. (aunque esto es opinion personal, no les baja puntos)
- Por ultimo y creo que mas importante, la complejidad final no es O(n *log n + n) es directamente O(n * log n), ese error conceptual creo que tambien les tiro en contra a la hora de discutir su nota final. 

Siento que el tp estaba un poco incompleto, igualmente, no se desanimen por la nota que todavia faltan algunos tps para hacer y poder aprender mas. Estoy abierto a consultas, criticas, o si piensan que me equivoque en algo respecto a la correccion, me lo pueden hacer saber por slack o directamente por mi mail : temanuel@fi.uba.ar. Saludos chicos, y espero el tp2

**Comment by Sh4rkzDev** [comment]
Buenas tardes Tomas! Ahi hice correcciones en el informe y agregue un par cosas. Todo esta en el anexo como indica la pagina de entregas. Saludos!

**Comment by tomasemanuel** [comment]
Perfecto chicos, ahora esta mucho mas completo, en reentregas no se puede subir mas de un punto, pero si me hubiesen entregado este tp con el anexo les hubiera puesto un 9 o 10, pero tomen este tp para asimilar como serian las entregas de los otros, con pruebas de optimalidad, con pruebas de volumen, con definiciones y con sustento matematico (si es que pueden), pero sobretodo, demostrando porque su algoritmo es optimo cuando ustedes lo declaran asi. Habiendo dicho esto, les queda 7 en este tp.
